general.import = [
  "theme/catppuccin-frappe.toml"
]

[window]
dimensions = { columns = 160, lines = 60 }
padding = { x = 3, y = 3 }
dynamic_padding = true
option_as_alt = "OnlyLeft"

[font]
normal = { family="JetBrainsMono Nerd Font", style="Regular" }
size = 12

[env]
TERM = "xterm-256color"
